version: '2'
services:
  proxy:
    image: nginx:alpine
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/nginx/ssl:/etc/nginx/ssl:ro
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/html:/usr/share/nginx/html:ro
