---
- name: Searching for old compose.
  stat:
    path: /opt/kujirax/docker-compose.yml
  register: old_compose

- name: Halt to old compose
  shell: docker-compose down
  args:
    chdir: /opt/kujirax
  become: yes
  when: old_compose.stat.exists
  register: halt_old_compose
  changed_when: halt_old_compose.stdout == ""
  ignore_errors: yes

- name: Reboot docker
  service:
    name: docker
    state: restarted
  become: yes

- name: Remove old container.
  file:
    path: /opt/kujirax
    state: absent
  become: yes

- name: Migrate to new containers
  shell: mv /opt/.kujirax /opt/kujirax
  become: yes

- name: Create a common network
  docker_network:
    name: common_link
  become: yes

- name: Build new containers
  shell: docker-compose build
  args:
    chdir: /opt/kujirax
  become: yes
  register: build_new_compose
  changed_when: '"Building" in build_new_compose.stdout'

- name: Get up to new containers
  shell: docker-compose up -d
  args:
    chdir: /opt/kujirax
  become: yes
