---
- name: Run deferred setup to gather facts
  setup: 

- import_tasks: install.yml
- import_tasks: settings.yml

- name: Searching for a user-defined setup definition file.
  local_action:
    module: stat
    path: /root/roles/settings-atomic-host/tasks/_main.yml
  register: optfile

- name: Invoke for a user-defined setup definition file.
  include_tasks: /root/roles/settings-atomic-host/tasks/_main.yml
  when: optfile.stat.exists