---
- name: Create source directory if not exists.
  local_action:
    module: file
    path: "/root/{{ item }}"
    state: directory
  changed_when: no
  with_items:
  - certs
  - dhparam

- name: Create temporary directory for deploy.
  file:
    path: /opt/.kujirax
    state: directory
  become: yes

- name: Deploy files.
  copy:
    src: "/root/{{ item }}"
    dest: /opt/.kujirax/
  become: yes
  notify: Migrate proxy
  with_items:
  - certs
  - dhparam
  - html

- name: Deploy Docker Compose settings for proxy.
  template:
    src: docker-compose.yml
    dest: /opt/.kujirax/docker-compose.yml
  become: yes
  notify: Migrate proxy
  with_items:
  - inventory_hostname: "{{ inventory_hostname }}"

- name: Deploy Dockerfile for proxy.
  template:
    src: Dockerfile
    dest: /opt/.kujirax/Dockerfile
  become: yes
  notify: Migrate proxy
