---
- name: Create kujirax directory
  file:
    path: "{{ item }}"
    state: directory
  become: yes
  with_items:
  - /opt/kujirax/proxy/conf

- name: Deploy config file for NGINX.
  template:
    src: default.conf
    dest: /opt/kujirax/proxy/conf/default.conf
  become: yes
  notify: Restart NGINX

- name: Searching for a user-defined HTML files.
  local_action:
    module: stat
    path: ~/html
  register: user_html

- name: Deploy user-defined HTML files.
  copy:
    src: ~/html
    dest: /opt/kujirax/proxy/
  become: yes
  when: user_html.stat.isdir
  notify: Restart NGINX
