---
- name: Create kujirax directory
  file:
    path: "{{ item }}"
    state: directory
  become: yes
  with_items:
  - /opt/kujirax/proxy/conf/apps
  - /opt/kujirax/proxy/tls

- name: Deploy config file for NGINX.
  template:
    src: default.conf
    dest: /opt/kujirax/proxy/conf/default.conf
  become: yes
  notify: Restart NGINX

- name: Deploy HTML files of index.
  copy:
    src: ~/html
    dest: /opt/kujirax/proxy/
  become: yes
  notify: Restart NGINX
